config/routes.rb
ModuleSite::Application.routes.draw do
  resources :news

  devise_for :users
  root :to =>'home#index'

  

end

app/models/author_ship.rb
class AuthorShip < ActiveRecord::Base
  belongs_to :user
  belongs_to :news
end

app/models/news.rb
class News < ActiveRecord::Base
    has_many :photos
    has_many :author_ships
    has_many :users, through: :author_ships
    has_many :news_words
    has_many :words, through: :news_words
    has_many :news_sections
    has_many :sections, through: :news_sections
end

app/models/news_section.rb
class NewsSection < ActiveRecord::Base
  belongs_to :news
  belongs_to :section
end

app/models/news_word.rb
class NewsWord < ActiveRecord::Base
  belongs_to :news
  belongs_to :word
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :news
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :news_sections
  has_many :newses, through: :news_sections
  has_many :subscriptions
  has_many :users, through: :subscriptions
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :section
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :author_ships
  has_many :newses, through: :author_ships
  has_many :subscriptions
  has_many :sections, through: :subscriptions
end

app/models/word.rb
class Word < ActiveRecord::Base
  has_many :news_words
  has_many :newses, through: :news_words
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	helper_method :time_of_day
	
	def time_of_day
	time = Time.now.hour
	if time<6
		"night"
	elsif time < 11
		"morning"
	elsif time < 16
		"day"
	elsif time < 20
		"evening"
	else
		"night"
	end
  end
  
  def color_by_time
	period = time_of_day
	case period
		when "night" 
			"black"
		when "evening" 
			"#0A1451"
		when "day" 
			"#66296E"
		when "morning"
			"#8F0100"
	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   # GET /news
  # GET /news.json
  def index
	@newses = News.all.order(created_at: :desc)
	@period = time_of_day
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
	@newses = News.all.order(created_at: :desc)
	if	s = params[:section]
		ns = NewsSection.where(section_id: s)
		if ns
			@ns.each do |n|
				@newses.where(id: n.news_id).destroy
			end
		end	
	end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    puts params
    unless @news=News.where(id: params[:id]).first
      render text: "Page not found", :status => 404
    end
	unless @news.views_number
		@news.views_number=0
	end
	@news.views_number+=1
	@news.save
	@section_num = NewsSection.where(news_id: @news.id).first.section_id
	@section = Section.where(id: @section_num).first.name
  end

  # GET /news/new
  def new
    @news = News.new
	@section_num = NewsSection.new
  end

  # GET /news/1/edit
  def edit
    @news =News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render action: 'show', status: :created, location: @news }
      else
        format.html { render action: 'new' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
	@section_num = NewsSection.new(news_id:@news.id, section_id:params[:section_id])
	  if @section_num.save
		format.html { redirect_to @section_num, notice: 'News was successfully related with section.' }
        format.json { render action: 'show', status: :created, location: @section_num }
	  else
		format.html { render action: 'new' }
        format.json { render json: @section_num.errors, status: :unprocessable_entity }
	  end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
     @news =News.find(params[:id])
    respond_to do |format|
      if @news.update_attributes(news_params)
        puts 'news_params', news_params
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
	  
	@section_num = NewsSection.where(news_id:@news.id).first
	@section_num.update_attributes(section_id:params[:section_id])
	  if @section_num.save
		format.html { redirect_to @section_num, notice: 'News was successfully related with section.' }
        format.json { render action: 'show', status: :created, location: @section_num }
	  else
		format.html { render action: 'new' }
        format.json { render json: @section_num.errors, status: :unprocessable_entity }
	  end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
	@section_num = NewsSection.where(news_id:@news.id).first
	if @section_num
		@section_num.destroy()
	end
    @news.destroy()
    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:header, :news)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/home/index.html.erb
<%# строка с указанием начала дива для хэдера находится в application.html.erb%>
	<% if user_signed_in? %>
	<div class="registration">
		<span>Вы успешно вошли на сайт!</span>
		<%= link_to "Выйти", destroy_user_session_path, :method => :delete %> |
		<%= link_to 'Что нового?', new_news_path %> 
	</div>

	<% else %>
	<div class="registration">
		<%= link_to "Войти", new_user_session_path, :method => :get %>
		<%= link_to "Регистрация", new_user_registration_path, :method => :get %>
	</div>	
	<% end %>  
<h1>Последние новости:</h1>	
</div>
<div id="content">
<% @newses.each do |news| %>
	<div class="bordered"> 
        <div id="item_title">
			<h3><%=link_to news.header, news_path(news)%></h3>
		</div>
		<div id="news_text">
			<%= truncate(news.news , :length => 100) %>
		</div>
        <div id="item_controls">
			<%#= link_to 'Показать', news %>
			<% if user_signed_in? %>
			<%= link_to 'Редактировать', edit_news_path(news) %>
			<%= link_to 'Удалить', news, method: :delete, data: { confirm: 'Вы уверены?' } %>
			<% end %>
		</div>
	</div> 	
<% end %> 
</div>
<!--div id="menu">
dfjhdkjfhdkjfhdkjh
</div-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Module Work</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class = "<%= time_of_day%>">
	<div class="<%= time_of_day%>" id="header">
	<%= yield %>
	<div id="footer">
		Made by Dolgih Anastasya and Onischenko Elena, PZ-10-1, 2013
	</div>
</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<%# строка с указанием начала дива для хэдера находится в application.html.erb%>
	<% if user_signed_in? %>
	<div class="registration">
		<%= link_to "Выйти", destroy_user_session_path, :method => :delete %>
	</div>
	<% end %> 
<%= form_for @news do |f| %>
	<div class="input">
		Заголовок:<br>
		<%=f.text_field :header%>
	</div>
</div>

<div id="content">
	<div class="input">
		Текст:<br>
		<%=f.text_area :news%>
	</div>
	<div class="input">
		Категория:<br> 
		<%= select_tag(:section_id, options_from_collection_for_select(Section.all, :id, :name)) %>
	</div>
	<div class="input">
		<%=f.submit("Изменить")%>
	</div>
<%end%>
<%= link_to 'Показать', @news %> |
<%= link_to 'Назад', news_index_path %>
</div>

app/views/news/index.html.erb
<%# строка с указанием начала дива для хэдера находится в application.html.erb%>
	<% if user_signed_in? %>
	<div class="registration">
		<span>Вы успешно вошли на сайт!</span>
		<%= link_to "Выйти", destroy_user_session_path, :method => :delete %> |
		<%= link_to 'Что нового?', new_news_path %>
	</div>

	<% else %>
	<div class="registration">
		<%= link_to "Войти", new_user_session_path, :method => :get %>
		<%= link_to "Регистрация", new_user_registration_path, :method => :get %>
	</div>	
	<% end %>  
<h1>Последние новости:</h1>	
</div>

<div id="content" class="<%=@period%>">
<% @newses.each do |news| %>
<div class="bordered"> 
        <div id="item_title">
			<h3><%=link_to news.header, news_path(news)%></h3>
		</div>
		<div id="news_text">
			<%= truncate(news.news , :length => 100) %>
		</div>
		<% if user_signed_in? %>
        <div id="item_controls">
			<%= link_to 'Редактировать', edit_news_path(news) %>
			<%= link_to 'Удалить', news, method: :delete, data: { confirm: 'Вы уверены?' } %>
		</div>
		<% end %> 
</div>     
<% end %>
</div>
<div id="menu">
<%=link_to 'Искусство', news_index_path(section:1)%>
</div>

app/views/news/new.html.erb
<%# строка с указанием начала дива для хэдера находится в application.html.erb%>
	<% if user_signed_in? %>
	<div class="registration">
		<%= link_to "Выйти", destroy_user_session_path, :method => :delete %>
	</div>
	<% end %>  
<%= form_for @news do |f| %>
	<div class="input">
		Заголовок:<br>
		<%=f.text_field :header%>
	</div>
</div>

<div id="content">
	<div class="input">
		Текст:<br>
		<%=f.text_area :news%>
	</div>
	<div class="input">
		Категория:<br> 
		<%= select_tag(:section_id, options_from_collection_for_select(Section.all, :id, :name)) %>
	</div>
	<div class="input">
		<%=f.submit("Создать")%>
	</div>
<%end%>
<%= link_to 'Назад', news_index_path %>
</div>

app/views/news/show.html.erb
<%# строка с указанием начала дива для хэдера находится в application.html.erb%>
<% if user_signed_in? %>
	<div class="registration">
		<span>Вы успешно вошли на сайт!</span>
		<%= link_to "Выйти", destroy_user_session_path, :method => :delete %>
		<%#= link_to "Каталог" ,news_index_path, :method=>:get %>
	</div>

	<% else %>
	<div class="registration">
		<%= link_to "Войти", new_user_session_path, :method => :get %>
		<%= link_to "Регистрация", new_user_registration_path, :method => :get %>
	</div>	
	<% end %>  
<h1><%=@news.header%></h1>
</div>


<div id="content">
<p>Категория: <%= @section%></p>
  <div class="bordered"> 
	<p><%= @news.news%> </p>
  </div>
  <p>Количество просмотров:<%= @news.views_number%>  </p>
  <p>Создано:<%= @news.created_at%>  </p>
<% if user_signed_in? %>
	<%= link_to 'Редактировать', edit_news_path(@news) %> |
<% end %>
<%= link_to 'Назад', news_index_path %>
</div>